config = {
    "debug"                            : False,
    "seed"                             : 0,
    "wandb.use"                        : False,
    "wandb.run_id"                     : None,
    "project"                          : "2d-slice-networks",
    "result_folder"                    : "result",
    "mode"                             : ["test", "train"],

    "data.name"                        : "adni_ad",
    "data.root_path"                    : "<root path of the data folder>",
    "data.train_csv"                    : "data/adni/train.csv",
    "data.test_csv"                     : "data/adni/test.csv",
    "data.valid_csv"                    : "data/adni/valid.csv",
    "data.train_num_sample"            : -1,
    "data.frame_keep_style"            : "random",
    "data.frame_keep_fraction"         : 1,
    "data.frame_dim"                   : 1,
    "data.noise_percent"               : 0,

    "model.name"                       : "binary_classifier",

    "model.arch.file"                  : "src/arch/adni/adni_3d.py",
    "model.arch.lstm_feat_dim"          : 2,
    "model.arch.lstm_latent_dim"        : 128,
    "model.arch.attn_dim"               : 32,
    "model.arch.attn_num_heads"         : 1,
    "model.arch.attn_drop"              : False,
    "model.arch.agg_fn"                 : "attention",
    "model.arch.use_position_encoding"  : False,
    "model.arch.encoder_2d"             : "encoder1",
    "model.arch.load_pretrained_encoder": False,

    "train.batch_size"                 : 8,
    "train.patience"                   : 100,
    "train.max_epoch"                  : 100,
    "train.optimizer"                  : "adam",
    "train.lr"                         : 1e-4,
    "train.weight_decay"               : 1e-4,
    "train.save_strategy"              : ["best", "last"],
    "train.log_every"                  : 100,
    "train.stopping_criteria"          : "accuracy",
    "train.stopping_criteria_direction": "bigger",
    "train.gradient_norm_clip"         : -1,

    "test.batch_size"                  : 8,
    "test.eval_model"                  : "best",
    }